name: .NET Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: ['Release']
        platform: ['Any CPU', 'x64', 'ARM64']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build and Upload Artifact
      run: |
        msbuild -t:restore /p:GitFlow="Github Action"
        msbuild -target:"Ink Canvas Annotation" /p:Configuration=${{ matrix.configuration }} /p:Platform="${{ matrix.platform }}" /p:GitFlow="Github Action"
      env:
        Configuration: ${{ matrix.configuration }}
